// Regenerates src/cases.js from the cells/ tree.
//
// Vite's ?raw imports have to be static, so the import list cannot be built at
// runtime — but it can be generated. Adding a cell is therefore: drop the .md
// in cells/<register>/, run `npm run cases`. Nothing is typed twice.
import { readdirSync, readFileSync, writeFileSync, statSync } from "node:fs";
import { join, resolve } from "node:path";

const ROOT = resolve(import.meta.dirname, "..");
const CELLS_DIR = join(ROOT, "cells");
const OUT = join(ROOT, "src", "cases.js");

// Condition metadata. A register need not have every one of these; a missing
// file simply leaves that panel empty.
const CONDITIONS = [
  { slug: "A-opus-chat", label: "A · Opus, chat", sub: "written in chat, contaminated baseline", band: "cold" },
  { slug: "A-opus-agent", label: "A · Opus, agent", sub: "subagent, skill suppressed", band: "cold" },
  { slug: "A-sonnet-agent", label: "A · Sonnet, agent", sub: "subagent, skill suppressed", band: "cold" },
  { slug: "B-opus-chat", label: "B · Opus, chat", sub: "written in chat", band: "skill" },
  { slug: "B-opus-agent", label: "B · Opus, agent", sub: "subagent, skill loaded", band: "skill" },
  { slug: "B-sonnet-agent", label: "B · Sonnet, agent", sub: "subagent, skill loaded", band: "skill" },
];

const registers = readdirSync(CELLS_DIR)
  .filter((d) => statSync(join(CELLS_DIR, d)).isDirectory())
  .sort();

const ident = (reg, slug) => reg.replace(/[^a-z0-9]/gi, "") + slug.replace(/[^a-z0-9]/gi, "");

const imports = [];
const cases = [];

for (const reg of registers) {
  const dir = join(CELLS_DIR, reg);
  const meta = JSON.parse(readFileSync(join(dir, "meta.json"), "utf8"));
  const present = CONDITIONS.filter((c) => {
    try {
      return statSync(join(dir, `${c.slug}.md`)).isFile();
    } catch {
      return false;
    }
  });
  for (const c of present) {
    imports.push(`import ${ident(reg, c.slug)} from "../cells/${reg}/${c.slug}.md?raw";`);
  }
  cases.push(
    [
      "  {",
      `    name: ${JSON.stringify(meta.name)},`,
      `    register: ${JSON.stringify(reg)},`,
      `    prompt: ${JSON.stringify(meta.prompt)},`,
      "    cells: {",
      ...present.map((c) => `      ${JSON.stringify(c.slug)}: ${ident(reg, c.slug)},`),
      "    },",
      "  },",
    ].join("\n")
  );
  console.log(`${reg.padEnd(16)} ${present.length} cells  ${meta.name}`);
}

const out = [
  "// GENERATED by scripts/gen-cases.mjs — do not edit by hand.",
  "// Cell text lives in cells/<register>/<condition>.md and is imported at build",
  "// time, so the panels and the files on disk cannot drift apart.",
  "",
  ...imports,
  "",
  "// label/sub/band describe the condition; text comes from the files above.",
  "// A register may be missing conditions — its `cells` map simply omits them.",
  "export const CELLS = [",
  ...CONDITIONS.map((c) => `  { slug: ${JSON.stringify(c.slug)}, label: ${JSON.stringify(c.label)}, sub: ${JSON.stringify(c.sub)}, band: ${JSON.stringify(c.band)} },`),
  "];",
  "",
  "export const CASES = [",
  ...cases,
  "];",
  "",
].join("\n");

writeFileSync(OUT, out);
console.log(`\nwrote ${OUT} — ${registers.length} registers, ${imports.length} cells`);
