// GENERATED by scripts/gen-cases.mjs — do not edit by hand.
// Cell text lives in cells/<register>/<condition>.md and is imported at build
// time, so the panels and the files on disk cannot drift apart.

import academicAopusagent from "../cells/academic/A-opus-agent.md?raw";
import academicAsonnetagent from "../cells/academic/A-sonnet-agent.md?raw";
import academicBopusagent from "../cells/academic/B-opus-agent.md?raw";
import academicBsonnetagent from "../cells/academic/B-sonnet-agent.md?raw";
import correspondenceAopusagent from "../cells/correspondence/A-opus-agent.md?raw";
import correspondenceAsonnetagent from "../cells/correspondence/A-sonnet-agent.md?raw";
import correspondenceBopusagent from "../cells/correspondence/B-opus-agent.md?raw";
import correspondenceBsonnetagent from "../cells/correspondence/B-sonnet-agent.md?raw";
import hybridAopusagent from "../cells/hybrid/A-opus-agent.md?raw";
import hybridAsonnetagent from "../cells/hybrid/A-sonnet-agent.md?raw";
import hybridBopusagent from "../cells/hybrid/B-opus-agent.md?raw";
import hybridBsonnetagent from "../cells/hybrid/B-sonnet-agent.md?raw";
import literaryAopuschat from "../cells/literary/A-opus-chat.md?raw";
import literaryAopusagent from "../cells/literary/A-opus-agent.md?raw";
import literaryAsonnetagent from "../cells/literary/A-sonnet-agent.md?raw";
import literaryBopuschat from "../cells/literary/B-opus-chat.md?raw";
import literaryBopusagent from "../cells/literary/B-opus-agent.md?raw";
import literaryBsonnetagent from "../cells/literary/B-sonnet-agent.md?raw";
import technicalAopuschat from "../cells/technical/A-opus-chat.md?raw";
import technicalAopusagent from "../cells/technical/A-opus-agent.md?raw";
import technicalAsonnetagent from "../cells/technical/A-sonnet-agent.md?raw";
import technicalBopuschat from "../cells/technical/B-opus-chat.md?raw";
import technicalBopusagent from "../cells/technical/B-opus-agent.md?raw";
import technicalBsonnetagent from "../cells/technical/B-sonnet-agent.md?raw";

// label/sub/band describe the condition; text comes from the files above.
// A register may be missing conditions — its `cells` map simply omits them.
export const CELLS = [
  { slug: "A-opus-chat", label: "A · Opus, chat", sub: "written in chat, contaminated baseline", band: "cold" },
  { slug: "A-opus-agent", label: "A · Opus, agent", sub: "subagent, skill suppressed", band: "cold" },
  { slug: "A-sonnet-agent", label: "A · Sonnet, agent", sub: "subagent, skill suppressed", band: "cold" },
  { slug: "B-opus-chat", label: "B · Opus, chat", sub: "written in chat", band: "skill" },
  { slug: "B-opus-agent", label: "B · Opus, agent", sub: "subagent, skill loaded", band: "skill" },
  { slug: "B-sonnet-agent", label: "B · Sonnet, agent", sub: "subagent, skill loaded", band: "skill" },
];

export const CASES = [
  {
    name: "Academic abstract",
    register: "academic",
    prompt: "Write a ~300 word abstract for a paper arguing that published latency benchmarks for distributed databases are not reproducible across deployment environments. Academic register. No invented numbers or citations.",
    cells: {
      "A-opus-agent": academicAopusagent,
      "A-sonnet-agent": academicAsonnetagent,
      "B-opus-agent": academicBopusagent,
      "B-sonnet-agent": academicBsonnetagent,
    },
  },
  {
    name: "Correspondence",
    register: "correspondence",
    prompt: "Write a ~250 word email to a long-standing customer declining their request for a custom uptime guarantee, without promising anything you have not already committed to. Professional register.",
    cells: {
      "A-opus-agent": correspondenceAopusagent,
      "A-sonnet-agent": correspondenceAsonnetagent,
      "B-opus-agent": correspondenceBopusagent,
      "B-sonnet-agent": correspondenceBsonnetagent,
    },
  },
  {
    name: "Technical essay",
    register: "hybrid",
    prompt: "Write the opening ~450 words of a blog post about why on-call rotations decay over time, holding literary rhythm and technical accuracy at the same time. First person is allowed. No invented statistics.",
    cells: {
      "A-opus-agent": hybridAopusagent,
      "A-sonnet-agent": hybridAsonnetagent,
      "B-opus-agent": hybridBopusagent,
      "B-sonnet-agent": hybridBsonnetagent,
    },
  },
  {
    name: "Literary nonfiction",
    register: "literary",
    prompt: "Write the opening ~400 words of a literary nonfiction essay about the night a production system failed, moving from scene toward reflection on how organizations decide what counts as an emergency. First person. No invented statistics.",
    cells: {
      "A-opus-chat": literaryAopuschat,
      "A-opus-agent": literaryAopusagent,
      "A-sonnet-agent": literaryAsonnetagent,
      "B-opus-chat": literaryBopuschat,
      "B-opus-agent": literaryBopusagent,
      "B-sonnet-agent": literaryBsonnetagent,
    },
  },
  {
    name: "Technical authority",
    register: "technical",
    prompt: "Write the opening ~450 words of a technical essay arguing that adaptive re-planning in query engines is undervalued, largely because static plan quality is so much easier to benchmark. Argumentative register. No specific numbers or citations.",
    cells: {
      "A-opus-chat": technicalAopuschat,
      "A-opus-agent": technicalAopusagent,
      "A-sonnet-agent": technicalAsonnetagent,
      "B-opus-chat": technicalBopuschat,
      "B-opus-agent": technicalBopusagent,
      "B-sonnet-agent": technicalBsonnetagent,
    },
  },
];
